export type EntityState = 'idle' | 'patrol' | 'alert' | 'chase' | 'attack' | 'return';

export interface EntityDef {
  id: string;
  name: string;
  entityNumber: number;
  speed: number;
  chaseSpeed: number;
  detectionRadius: number;
  hearingRadius: number;
  visionAngle: number;
  damage: number;
  hp: number;
  color: string;
  emissive: string;
  emissiveIntensity: number;
  shape: 'sphere' | 'box' | 'cylinder' | 'cone';
  scale: [number, number, number];
  hostile: boolean;
  description: string;
}

export const ENTITIES: Record<string, EntityDef> = {
  smiler: {
    id: 'smiler',
    name: 'Smiler',
    entityNumber: 3,
    speed: 1.5,
    chaseSpeed: 5,
    detectionRadius: 12,
    hearingRadius: 8,
    visionAngle: 90,
    damage: 35,
    hp: 40,
    color: '#0a0a0a',
    emissive: '#ffff00',
    emissiveIntensity: 2,
    shape: 'sphere',
    scale: [0.4, 0.4, 0.4],
    hostile: true,
    description: 'Glowing eyes in the dark. Do not approach.',
  },
  hound: {
    id: 'hound',
    name: 'Hound',
    entityNumber: 8,
    speed: 2.5,
    chaseSpeed: 7,
    detectionRadius: 15,
    hearingRadius: 20,
    visionAngle: 120,
    damage: 25,
    hp: 60,
    color: '#2a2020',
    emissive: '#ff3300',
    emissiveIntensity: 0.5,
    shape: 'box',
    scale: [0.6, 0.5, 1.2],
    hostile: true,
    description: 'Fast quadruped. Relies heavily on hearing.',
  },
  facelings: {
    id: 'facelings',
    name: 'Faceling',
    entityNumber: 9,
    speed: 1,
    chaseSpeed: 2,
    detectionRadius: 6,
    hearingRadius: 4,
    visionAngle: 60,
    damage: 10,
    hp: 20,
    color: '#c8b090',
    emissive: '#000000',
    emissiveIntensity: 0,
    shape: 'cylinder',
    scale: [0.3, 1.6, 0.3],
    hostile: false,
    description: 'Humanoid without facial features. Smooth featureless head.',
  },
  'skin-stealer': {
    id: 'skin-stealer',
    name: 'Skin-Stealer',
    entityNumber: 10,
    speed: 0.5,
    chaseSpeed: 6,
    detectionRadius: 10,
    hearingRadius: 5,
    visionAngle: 180,
    damage: 45,
    hp: 80,
    color: '#8a6050',
    emissive: '#ff6600',
    emissiveIntensity: 0.3,
    shape: 'cylinder',
    scale: [0.35, 1.7, 0.35],
    hostile: true,
    description: 'Tall humanoid with stretched skin, elongated limbs, glowing orange eyes.',
  },
  wretches: {
    id: 'wretches',
    name: 'Wretch',
    entityNumber: 15,
    speed: 0.8,
    chaseSpeed: 2.5,
    detectionRadius: 8,
    hearingRadius: 6,
    visionAngle: 90,
    damage: 15,
    hp: 25,
    color: '#3a3a2a',
    emissive: '#444400',
    emissiveIntensity: 0.2,
    shape: 'sphere',
    scale: [0.5, 0.5, 0.5],
    hostile: true,
    description: 'Hunched emaciated humanoid, arms dragging, pale yellowish skin.',
  },
// ENTITY_CONTINUE
  crawlers: {
    id: 'crawlers',
    name: 'Crawler',
    entityNumber: 17,
    speed: 2,
    chaseSpeed: 5.5,
    detectionRadius: 6,
    hearingRadius: 3,
    visionAngle: 45,
    damage: 30,
    hp: 35,
    color: '#1a1a1a',
    emissive: '#880000',
    emissiveIntensity: 0.8,
    shape: 'box',
    scale: [0.8, 0.2, 0.8],
    hostile: true,
    description: 'Flat black mass on ceiling with spindly legs. Single red eye.',
  },
  dullers: {
    id: 'dullers',
    name: 'Duller',
    entityNumber: 6,
    speed: 0.5,
    chaseSpeed: 1,
    detectionRadius: 5,
    hearingRadius: 3,
    visionAngle: 360,
    damage: 5,
    hp: 50,
    color: '#606060',
    emissive: '#404040',
    emissiveIntensity: 0.1,
    shape: 'cylinder',
    scale: [0.4, 1.5, 0.4],
    hostile: true,
    description: 'Gray featureless humanoid with visible dullness aura.',
  },
  partygoers: {
    id: 'partygoers',
    name: 'Partygoer',
    entityNumber: 67,
    speed: 1.2,
    chaseSpeed: 4,
    detectionRadius: 14,
    hearingRadius: 10,
    visionAngle: 120,
    damage: 40,
    hp: 55,
    color: '#ffee00',
    emissive: '#ffee00',
    emissiveIntensity: 1,
    shape: 'cylinder',
    scale: [0.3, 1.6, 0.3],
    hostile: true,
    description: 'Bright yellow humanoid with wide smile and party hat. Appears friendly but lethal.',
  },
  'death-rats': {
    id: 'death-rats',
    name: 'Death Rat',
    entityNumber: 24,
    speed: 3,
    chaseSpeed: 5,
    detectionRadius: 7,
    hearingRadius: 12,
    visionAngle: 180,
    damage: 8,
    hp: 10,
    color: '#2a2020',
    emissive: '#ff0000',
    emissiveIntensity: 0.4,
    shape: 'sphere',
    scale: [0.2, 0.15, 0.3],
    hostile: true,
    description: 'Small dark rodent with glowing red eyes and hairless tail.',
  },
// ENTITY_CONTINUE_2
  deathmoths: {
    id: 'deathmoths',
    name: 'Deathmoth',
    entityNumber: 4,
    speed: 2,
    chaseSpeed: 3.5,
    detectionRadius: 10,
    hearingRadius: 5,
    visionAngle: 360,
    damage: 12,
    hp: 15,
    color: '#8a7a60',
    emissive: '#aa8844',
    emissiveIntensity: 0.3,
    shape: 'cone',
    scale: [0.5, 0.3, 0.5],
    hostile: true,
    description: 'Large moth with dusty brown wings and glowing amber eyes.',
  },
  jerry: {
    id: 'jerry',
    name: 'Jerry',
    entityNumber: 7,
    speed: 0.8,
    chaseSpeed: 0.8,
    detectionRadius: 8,
    hearingRadius: 6,
    visionAngle: 120,
    damage: 0,
    hp: 999,
    color: '#5588aa',
    emissive: '#3366aa',
    emissiveIntensity: 0.5,
    shape: 'cylinder',
    scale: [0.3, 1.5, 0.3],
    hostile: false,
    description: 'Friendly blue-tinted humanoid in casual clothes. Offers guidance.',
  },
  clumps: {
    id: 'clumps',
    name: 'Clump',
    entityNumber: 5,
    speed: 0.3,
    chaseSpeed: 1.5,
    detectionRadius: 4,
    hearingRadius: 6,
    visionAngle: 360,
    damage: 20,
    hp: 70,
    color: '#5a3030',
    emissive: '#330000',
    emissiveIntensity: 0.2,
    shape: 'sphere',
    scale: [0.6, 0.6, 0.6],
    hostile: true,
    description: 'Mass of tangled limbs and flesh hanging in tight spaces. Multiple arms reach outward.',
  },
  windows: {
    id: 'windows',
    name: 'The Window',
    entityNumber: 2,
    speed: 0,
    chaseSpeed: 0,
    detectionRadius: 6,
    hearingRadius: 3,
    visionAngle: 180,
    damage: 30,
    hp: 100,
    color: '#2a3a4a',
    emissive: '#4488cc',
    emissiveIntensity: 0.6,
    shape: 'box',
    scale: [0.8, 1.2, 0.1],
    hostile: true,
    description: 'Sentient window frame embedded in walls. Glows with hostile blue light. Attacks when approached.',
  },
};